
#!/usr/bin/env python3
"""Patches the AndroidManifest.xml generated by `flutter create` with the
permissions and metadata this browser needs.

Why this exists: this repository intentionally does NOT commit the
`android/` platform folder (see README + .gitignore) because it contains a
binary Gradle wrapper jar that has to come from the Flutter SDK/tooling.
Instead, CI (and local dev — see README) runs:

    flutter create --platforms=android --org com.privacybrowser .

to (re)generate `android/`, then runs this script to apply the small set of
changes a browser app needs on top of the stock template: INTERNET /
network-state permissions, an app label, and disabling cleartext traffic.
"""

import re
import sys
from pathlib import Path

MANIFEST_PATH = Path("android/app/src/main/AndroidManifest.xml")

REQUIRED_PERMISSIONS = [
    '<uses-permission android:name="android.permission.INTERNET"/>',
    '<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>',
]

APP_LABEL = "Privacy Browser"


def main() -> None:
    if not MANIFEST_PATH.exists():
        sys.exit(
            f"ERROR: {MANIFEST_PATH} not found.\n"
            "Run `flutter create --platforms=android .` first."
        )

    text = MANIFEST_PATH.read_text(encoding="utf-8")

    manifest_open = re.search(r"<manifest[^>]*>", text)
    if manifest_open:
        insert_at = manifest_open.end()
        missing = [
            perm for perm in REQUIRED_PERMISSIONS
            if perm.split('"')[1] not in text
        ]
        if missing:
            block = "\n    " + "\n    ".join(missing)
            text = text[:insert_at] + block + text[insert_at:]

    if 'android:label="' in text:
        text = re.sub(
            r'android:label="[^"]*"', f'android:label="{APP_LABEL}"', text, count=1
        )

    if "android:usesCleartextTraffic" not in text:
        text = re.sub(
            r"(<application\b)",
            r'\1\n        android:usesCleartextTraffic="false"',
            text,
            count=1,
        )

    MANIFEST_PATH.write_text(text, encoding="utf-8")
    print(f"Patched {MANIFEST_PATH}")


if __name__ == "__main__":
    main()
